#!/bin/bash -eu

main() {
  om -v

  metadata="${PWD}/env-state/metadata"
  vars_file="${PWD}/env-state/vars-file"
  cat "${metadata}" | yq -r .stable_config | jq -r . > "${vars_file}"

  config="${PWD}/paving/ci/configuration/${IAAS}/ops-manager.yml"
  updated_config="${PWD}/config/ops-manager.yml"

  if [ "${IAAS}" == "gcp" ]; then
    key="$(mktemp)"
    echo "${GCP_SERVICE_ACCOUNT_KEY}" > "${key}"

    bosh interpolate "${config}" \
      --var-file gcp_service_account_key="${key}" \
      --vars-file "${vars_file}" \
      > "${updated_config}"

  else
    bosh interpolate "${config}" --vars-file "${vars_file}" > "${updated_config}"
  fi
}

main "$@"
