#!/bin/bash -eu

main() {
  om -v

  metadata="${PWD}/env-state/metadata"

  config="${PWD}/paving/ci/configuration/${IAAS}/ops-manager.yml"
  updated_config="${PWD}/env-state/ops-manager.yml"

  if [ "${IAAS}" == "gcp" ]; then
    key="${PWD}/env-state/key"
    echo "${GCP_SERVICE_ACCOUNT_KEY}" > "${key}"

    bosh interpolate "${config}" \
      --var-file gcp_service_account_key="${key}" \
      --var project="$(cat "${metadata}" | yq -r .stable_config | jq -r .project)" \
      --var region="$(cat "${metadata}" | yq -r .stable_config | jq -r .region)" \
      --var zone="$(cat "${metadata}" | yq -r .stable_config | jq -r .availability_zones[0])" \
      --var vpc_subnet="$(cat "${metadata}" | yq -r .stable_config | jq -r .public_subnet_name)" \
      --var public_ip="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_public_ip)" \
      > "${updated_config}"

    rm "${key}"

  elif [ "${IAAS}" == "aws" ]; then
    bosh interpolate "${config}" \
      --var access_key="${AWS_ACCESS_KEY}" \
      --var secret_key="${AWS_SECRET_KEY}" \
      --var region="$(cat "${metadata}" | yq -r .stable_config | jq -r .region)" \
      --var zone="$(cat "${metadata}" | yq -r .stable_config | jq -r .availability_zones[0])" \
      --var vpc_subnet_id="$(cat "${metadata}" | yq -r .stable_config | jq -r .subnet_public_ids[0])" \
      --var public_ip="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_public_ip)" \
      --var key_pair_name="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_key_pair_name)" \
      --var security_group_ids="[$(cat "${metadata}" | yq -r .stable_config | jq -r .security_group_ops_manager_id)]" \
      --var iam_instance_profile_name="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_iam_instance_profile_name)" \
      > "${updated_config}"

  elif [ "${IAAS}" == "azure" ]; then
    bosh interpolate "${config}" \
      --var tenant_id="${AZURE_TENANT_ID}" \
      --var subscription_id="${AZURE_SUBSCRIPTION_ID}" \
      --var client_id="${AZURE_CLIENT_ID}" \
      --var client_secret="${AZURE_CLIENT_SECRET}" \
      --var location="$(cat "${metadata}" | yq -r .stable_config | jq -r .location)" \
      --var resource_group_name="$(cat "${metadata}" | yq -r .stable_config | jq -r .resource_group_name)" \
      --var management_subnet_id="$(cat "${metadata}" | yq -r .stable_config | jq -r .management_subnet_id)" \
      --var ops_manager_public_key="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_public_key)"  \
      --var ops_manager_public_ip="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_public_ip)"  \
      --var ops_manager_security_group_name="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_security_group_name)" \
      --var ops_manager_container_name="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_public_ip)" \
      --var ops_manager_storage_account_name="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_storage_account_name)" \
      --var ops_manager_container_name="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_container_name)" \
      > "${updated_config}"
  fi
}

main "$@"
