#!/bin/bash -eu

main() {
  om -v

  metadata="${PWD}/env-state/metadata"
  vars_file="${PWD}/env-state/vars-file"

  cat "${metadata}" | yq -r .stable_config | jq -r . > "${vars_file}"

  config="${PWD}/paving/ci/configuration/${IAAS}/director.yml"
  updated_config="${PWD}/env-state/director.yml"

  bosh interpolate "${config}" --vars-file "${vars_file}" > "${updated_config}"
}

main "$@"
