#!/bin/bash -exu

function set_opsman_dns() {
  metadata="${PWD}/env-state/metadata"

  opsman_dns=$(jq -r .ops_manager_dns < "${metadata}") || true

  # if yq failed then it means we might be setting dns for vsphere
  if [ -z "${opsman_dns}" ] || [ "${opsman_dns}" == "null" ]; then
    opsman_dns=$(yq -r .opsman.hostname < "${metadata}")
  fi
}

function main() {
  if [ -n "${USE_VPN:-}" ] && [ "$USE_VPN" == "true" ] ; then
    source ./cp-ci/ci/tasks/configure-vpn
    trap kill_vpn RETURN
  fi

  set_opsman_dns
  om -t "https://${opsman_dns}" -k apply-changes -i ${IGNORE_WARNINGS}
}

main "$@"
