#!/bin/bash -exu

function main() {
  metadata="${PWD}/env-state/metadata"
  opsman_dns=$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_dns)

  om -t "https://${opsman_dns}" -k apply-changes
}

main "$@"
