#!/bin/bash -eu

main() {
  om -v

  metadata="${PWD}/env-state/metadata"
  om_target="$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_dns)"

  updated_env_yml="${PWD}/env/env.yml"
  updated_auth_config_file="${PWD}/config/auth.yml"

  bosh interpolate "${ENV_YML}" \
    --var om_username="${OM_USERNAME}" \
    --var om_password="${OM_PASSWORD}" \
    --var om_target="${om_target}" \
    > "${updated_env_yml}"

  bosh interpolate "${AUTH_CONFIG_FILE}" \
    --var om_username="${OM_USERNAME}" \
    --var om_password="${OM_PASSWORD}" \
    --var om_decryption_passphrase="passphrase" \
    > "${updated_auth_config_file}"
}

main "$@"
