#!/bin/bash -eu

main() {
  om -v

  metadata="${PWD}/env-state/metadata"
  vars_file="${PWD}/env-state/vars-file"
  cat "${metadata}" | yq -r .stable_config | jq -r . > "${vars_file}"
  om_target="$(cat "${vars_file}" | jq -r .ops_manager_dns)"

  updated_env_yml="${PWD}/env/env.yml"
  updated_auth_config_file="${PWD}/config/auth.yml"
  updated_director_config_path="${PWD}/config/director.yml"

  bosh interpolate "${ENV_YML}" \
    --var om_username="${OM_USERNAME}" \
    --var om_password="${OM_PASSWORD}" \
    --var om_target="${om_target}" \
    > "${updated_env_yml}"

  bosh interpolate "${AUTH_CONFIG_FILE}" \
    --var om_username="${OM_USERNAME}" \
    --var om_password="${OM_PASSWORD}" \
    --var om_decryption_passphrase="passphrase" \
    > "${updated_auth_config_file}"

  bosh interpolate "${DIRECTOR_CONFIG_PATH}" \
    --vars-file "${vars_file}" \
    > "${updated_director_config_path}"
}

main "$@"
