#!/bin/bash -exu

main() {
  opsman_image=$(bosh int ${PWD}/opsman-image/*${IAAS}*.yml --path "/${KEY}")
  iaas_lowercase=$(echo "${IAAS}" | awk '{print tolower($0)}')

  local output_key
  local prefix=""
  case "$iaas_lowercase" in
  aws)
    output_key=ops_manager_ami
    ;;
  gcp)
    prefix="https://storage.googleapis.com/"
    output_key=opsman_image_url
    ;;
  azure)
    output_key=ops_manager_image_uri
    ;;
  esac

  echo "${output_key}: ${prefix}${opsman_image}" > "${PWD}/tfvars/terraform.yml"
}

main "$@"
