#!/bin/sh -exu

main() {
  #https://github.com/pivotal-cf/reconfigure-pipeline/pull/4
  go get github.com/genevieve/reconfigure-pipeline@v0.26.0

  reconfigure-pipeline --target i --pipeline paving-gcp --config pipelines/gcp.yml --non-interactive

  reconfigure-pipeline --target i --pipeline paving-aws --config pipelines/aws.yml --non-interactive

  reconfigure-pipeline --target i --pipeline paving-azure --config pipelines/azure.yml --non-interactive
}

main
