#!/bin/sh -exu


main() {
  #https://github.com/pivotal-cf/reconfigure-pipeline/pull/4
  go get github.com/genevieve/reconfigure-pipeline@shared-folders

  fly --target i set-pipeline \
    --pipeline paving \
    --config pipelines/gcp.yml
}

main "$@"
