#!/bin/sh -exu

main() {
  #https://github.com/pivotal-cf/reconfigure-pipeline/pull/4
  go get github.com/genevieve/reconfigure-pipeline@v0.25.0

  reconfigure-pipeline --target i --pipeline paving --config pipelines/gcp.yml
}

main
