#!/bin/bash -exu

main() {
  om -v

  metadata="${PWD}/env-state/metadata"

  vars_file="${PWD}/env-state/vars-file"
  cat "${metadata}" | yq -r .stable_config | jq -r . > "${vars_file}"
  config="${DIRECTOR_YML}"
  updated_config="${PWD}/env-state/director.yml"
  bosh interpolate "${config}" --vars-file "${vars_file}" > "${updated_config}"

  ops_manager_dns=$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_dns)

  set +x
    om -t "https://${ops_manager_dns}" -k -o 30 configure-authentication -dp "${OM_PASSWORD}"
  set -x

  om -t "https://${ops_manager_dns}" -k configure-director --config "${updated_config}"
}

main "$@"
