#!/bin/bash -exu

main() {
  om -v

  metadata="${PWD}/env-state/metadata"
  opsman_dns=$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_dns)

  if [[ "${opsman_dns}" == "null" ]]; then
    echo "missing ops manager dns, exiting"
    exit 1
  fi

  set +x
    om -t "https://${opsman_dns}" -k -o 30 configure-authentication -dp "${OM_PASSWORD}"
  set -x

  om -t "https://${opsman_dns}" -k configure-director --config "${PWD}/env-state/director.yml"
}

main "$@"
