#!/bin/bash -exu

function main() {
  if [ -n "${USE_VPN:-}" ] && [ "$USE_VPN" == "true" ] ; then
    source ./cp-ci/ci/tasks/configure-vpn
    trap kill_vpn RETURN
  fi

  cwd=${PWD}

  pushd product
    version="$(unzip -p *.pivotal 'metadata/*.yml' | grep '^product_version:' | cut -d" " -f2 | sed 's/"//g')"
  popd

  product="$(ls -1 "${cwd}"/product/*.pivotal)"
  stemcell="$(ls -1 "${cwd}"/stemcell/*.tgz)"

  metadata="${PWD}/env-state/metadata"

  ops_manager_dns=$(jq -r .ops_manager_dns < "${metadata}") || true

  # generate-config
  bosh interpolate "${PRODUCT_YML}" --vars-file "${vars_file}" > "${updated_config}"

  # upload and stage product
  om -t "https://${ops_manager_dns}" -k upload-stemcell --stemcell "${stemcell}"
  om --request-timeout 7200 -t "https://${ops_manager_dns}" -k upload-product --product "${product}"
  om -t "https://${ops_manager_dns}" -k stage-product --product-name "${PRODUCT_NAME}" --product-version "${version}"

  # configure-product
  om -t "https://${ops_manager_dns}" -k configure-product --config "${updated_config}"
}

main "$@"
